apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-deploy-app
spec:
  workspaces:
  - name: source
  steps:
    - name: kubectl-apply-app-configuration
      image: gcr.io/cloud-builders/kubectl
      script: |
        echo "----------- INFO -----------"
        kubectl get pods --all-namespaces
        ls -al
        echo $(workspaces.source.path)
        ls -la $(workspaces.source.path)
        # kubectl delete -f $(workspaces.source.path)/infra/app
        echo "----------- DEPLOY -----------"
        kubectl apply -f $(workspaces.source.path)/infra/app
        echo "----------- CHECK -----------"
        kubectl describe pod app-pod
        kubectl logs app-pod