apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-setup-infra
spec:
  workspaces:
  - name: source
  steps:
    - name: list-files
      image: zshusers/zsh:4.3.15
      script: |
        #!/usr/bin/env zsh
        pwd
        ls -al
        echo $(workspaces.source.path)
        ls -la $(workspaces.source.path)
    - name: localstack-test
      image: python:3
      script: |
        pip install -r $(workspaces.source.path)/requirements.txt
        INFRA_LOCALSTACK_ADDRESS=172.17.0.2 pytest $(workspaces.source.path)/infra/localstack
