apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-setup-infra
spec:
  workspaces:
  - name: source
  steps:
    - name: list-files
      image: zshusers/zsh:4.3.15
      script: |
        #!/usr/bin/env zsh
        pwd
        ls -al
        echo $(workspaces.source.path)
        ls -la $(workspaces.source.path)
    - name: localstack-start
      image: ubuntu
      command:
        - echo
      args:
        - "step - start Localstack"
    - name: localstack-test
      image: ubuntu
      command:
        - echo
      args:
        - "step - test Localstack"