apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-run-app
spec:
  steps:
    - name: pull-run-docker-container
      image: docker
      script: |
        docker pull sebaczech/python-localstack-client:main
        docker images
        docker run --name python-localstack-client --rm -e LOCALSTACK_HOST=172.17.0.2 sebaczech/python-localstack-client:main
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
  sidecars:
    - image: docker:dind
      name: server
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}