apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-cd-app
spec:
  description: |
    CD pipeline for Cloud Native application
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
    default: https://github.com/sebastianczech/Cloud-Native-CI-CD
  - name: branch-name
    type: string
    description: The git branch to clone.
    default: main
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the repo's README.md file to be read.
  tasks:
  - name: info-pipeline-cd-app
    workspaces:
    - name: source
      workspace: shared-data  
    taskSpec:
      workspaces:
      - name: source
      steps:    
      - name: info-message
        image: ubuntu
        command:
          - echo
        args:
          - "CD pipeline for Cloud Native application"
  - name: clone-repo
    runAfter: ["info-pipeline-cd-app"]
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.branch-name)
  - name: setup-infra
    runAfter: ["clone-repo"]
    taskRef:
      name: task-setup-infra
    workspaces:
    - name: source
      workspace: shared-data
  - name: deploy-app
    runAfter: ["setup-infra"]
    taskRef:
      name: task-deploy-app
    workspaces:
    - name: source
      workspace: shared-data
  - name: run-app
    runAfter: ["deploy-app"]
    taskRef:
      name: task-run-app
