apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-deploy-app
spec:
  workspaces:
  - name: source
  steps:
    - name: kubectl-apply-app-configuration
      image: gcr.io/cloud-builders/kubectl
      script: |
        echo $(workspaces.source.path)
        ls -la $(workspaces.source.path)
        kubectl delete -f $(workspaces.source.path)/infra/app/pod.yml --ignore-not-found=true
        kubectl apply -f $(workspaces.source.path)/infra/app/pod.yml
