apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: cloud-native-app
spec:
  containers:
    - name: app-container
      image: sebaczech/python-localstack-client:main
      imagePullPolicy: Always
      env:
      - name: LOCALSTACK_HOST
        value: "172.17.0.2"
